#!/bin/bash
echo "Launching Pre-Installation Script for 'Ringed- Preferences Bundle.'"
echo "Detecting if iDevice is Retina HD or Non-Retina SD."
if [ -a /Applications/Preferences.app/iconCache@2x.artwork ]
then
	echo "iDevice is Retina HD"
	echo "Backing up the Icon Mask for the icons in the iOS Settings App. (Preferences.app) for a Retina HD iDevice."
	mv /System/Library/PrivateFrameworks/MobileIcons.framework/TableIconMask@2x.png /System/Library/PrivateFrameworks/MobileIcons.framework/BackupTableIconMask@2x.png
else
	echo "iDevice is Non-Retina SD."
	echo "Backing up the Icon Mask for the icons in the iOS Settings App. (Preferences.app) for a Non-Retina SD device."
	mv /System/Library/PrivateFrameworks/MobileIcons.framework/TableIconMask.png /System/Library/PrivateFrameworks/MobileIcons.framework/BackupTableIconsMask.png
fi
echo "Backup Successful!"
echo "Closing Pre-Installation Script."
exit 0